# Generated by Django 5.2.17 on 2026-10-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(db_index=True, max_length=40)),
                ('product_id', models.IntegerField(db_index=True, null=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                ('parameters', models.JSONField(default=dict)),
                ('algorithm_version', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'analisis',
                'ordering': ['-analysis_date', '-id'],
            },
        ),
    ]
