# Generated by Django 5.2.17 on 2026-10-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('min_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_warning_days', models.PositiveIntegerField(blank=True, null=True)),
                ('overstock_days_of_cover', models.PositiveIntegerField(blank=True, null=True)),
                ('analysis_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('low_turnover_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('high_turnover_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('service_level_z', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('review_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('default_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_riesgo',
                'constraints': [models.UniqueConstraint(fields=('product_id', 'category_id'), name='uq_riesgo_producto_categoria')],
            },
        ),
    ]
