# Generated by Django 5.2.17 on 2026-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('location_id', models.SmallIntegerField(blank=True, null=True)),
                ('alert_type', models.CharField(choices=[('DESABASTO', 'Desabasto'), ('BAJO_STOCK', 'Bajo Stock'), ('SOBREINVENTARIO', 'Sobreinventario'), ('BAJA_ROTACION', 'Baja Rotacion'), ('CADUCIDAD_PROXIMA', 'Caducidad Proxima'), ('PRODUCTO_CADUCADO', 'Producto Caducado'), ('AGOTAMIENTO_ESTIMADO', 'Agotamiento Estimado')], max_length=30)),
                ('severity', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ATENDIDA', 'Atendida'), ('DESCARTADA', 'Descartada')], db_index=True, default='PENDIENTE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'severity'], name='idx_alerta_status_severity')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDIENTE')), fields=('dedup_key',), name='uq_alerta_pendiente_dedup')],
            },
        ),
    ]
