# Generated by Django 5.2.17 on 2026-10-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('forecast_date', models.DateField()),
                ('forecast_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_name', models.CharField(max_length=50)),
                ('model_version', models.CharField(max_length=20)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pronosticos',
                'ordering': ['forecast_date', 'product_id'],
                'constraints': [models.UniqueConstraint(fields=('product_id', 'forecast_date', 'model_name', 'model_version'), name='uq_pronostico_producto_fecha_modelo')],
            },
        ),
    ]
