# Generated by Django 5.2.17 on 2026-10-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forecast',
            index=models.Index(fields=['product_id', 'forecast_date'], name='idx_pronostico_producto_fecha'),
        ),
    ]
