# Generated by Django 5.2.17 on 2026-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64)),
                ('conversation_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('user_request', models.TextField(null=True)),
                ('tool', models.CharField(db_index=True, max_length=60)),
                ('parameters', models.JSONField()),
                ('service_executed', models.CharField(max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution_time_ms', models.FloatField()),
                ('success', models.BooleanField()),
                ('error', models.TextField(null=True)),
                ('result_summary', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'agent_tool_log',
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
