# Generated by Django 5.2.17 on 2026-10-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='toollog',
            index=models.Index(fields=['timestamp'], name='idx_tool_log_timestamp'),
        ),
    ]
