# Generated by Django 5.2.17 on 2026-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('location_id', models.SmallIntegerField(db_index=True)),
                ('lot_number', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('entry_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('CADUCADO', 'Caducado'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lotes',
                'constraints': [models.UniqueConstraint(fields=('product_id', 'location_id', 'lot_number'), name='uq_lote_producto_ubicacion_numero'), models.CheckConstraint(condition=models.Q(('expiration_date__isnull', True), ('expiration_date__gte', models.F('entry_date')), _connector='OR'), name='ck_lote_caducidad_posterior_entrada')],
            },
        ),
    ]
